### ISSUE TITLE
Incompatible with GNOME-Online-Accounts 3.34

### ISSUE THREAD

**Issue by Saroufim** [flathub/org.gnome.Todo#8]
With GOA 3.34 installed on the system, gnome-todo no longer displays any lists, not even the local ones. Downgrading to GOA 3.32 fixes the issue but this is not a proper solutio.

**Comment by mildred** [comment]
Just reported it as https://gitlab.gnome.org/GNOME/gnome-todo/issues/296

I believe this is a major issue with flatpaks. What happens if gnome-todo is started un a KDE environment ? I suspect it would not even work. At some point I wanted to test Kde apps and I faced the similar problem, I did not have the KDE daemons running in my GNOME session.

Compatibility across operating system versions and across desktop environment is not possible if the packaged apps depends on daemons from the user session. The daemons should be bundled within the flatpak.

**Comment by fedelibre** [comment]
Same problem here. I've installed the dev version org.gnome.TodoDevel from gnome-nightly and it works... the interface has improved a lot.

**Comment by JaneSmith** [comment]
I'm experiencing the same issue here. GNOME To Do just doesn't seem to work at all.

**Comment by corebots** [comment]
Just wanted to report that it's the same on gnome 3.36 sadly :(
